### ISSUE TITLE
"Pro-Mode" Option

### ISSUE THREAD

**Issue by skylandersNFC** [skylandersNFC/Skylanders-GUI-Tool#1]
I did some research and stumbled upon this "**Pro-Mode**" option, but just flipping the last byte of the "**example.key**" from **00** to **01**

![image](https://github.com/user-attachments/assets/95e76219-c936-44e4-a241-3412f85f77c6)
Here is the GUI result, witch the checkbox enabled on "Pro-Mode" and some extra buttons.

![image](https://github.com/user-attachments/assets/19c2dc24-b70e-4e8c-b6f6-bf9aebff9420)

@Pyrofer I was wondering if you can share some information regarding this option and how does it work exactly in the scope of extra features and such.

Gratitude

**Comment by Pyrofer** [comment]
Turning PRO mode enables changing certain figure stats. You can get "all" the money by clicking money.
You can get all the upgrades by clicking upgrades, level up by clicking level up. You can swap chosen path by clicking Path A/B and finally you can add and remove heroic quests.
It's been there from the start but just takes all the fun out of the game. Enjoy playing and levelling up by hand. It also wasn't updated for later games so level caps etc are not reflected in the upgrades. (it was based on SSA/Giants figures)

**Comment by skylandersNFC** [comment]
@Pyrofer Thank you kindly for explaining this :)
